version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: wizwin-zinpack-f2025-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - wizwin-network

  php:
    build: ./php
    container_name: wizwin-zinpack-f2025-php
    volumes:
      - ./src:/var/www/html
    networks:
      - wizwin-network

  db:
    build: ./db
    container_name: wizwin-zinpack-f2025-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: infoway@$$db
      MYSQL_DATABASE: infoway
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - wizwin-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wizwin-zinpack-f2025-admin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: infoway@$$db
    depends_on:
      - db
    networks:
      - wizwin-network

volumes:
  db_data:

networks:
  wizwin-network: