<?php

$sql = "CREATE TABLE $iw[home_scrap_table](
hs_no int(11) NOT NULL auto_increment,
ep_code varchar(30) NOT NULL default '',
gp_code varchar(30) NOT NULL default '',
hm_code varchar(30) NOT NULL default '',
hs_scrap varchar(10) NOT NULL default '',
hs_name varchar(255) NOT NULL default '',
hs_order int(11) NOT NULL default '0',
hs_style tinyint(4) NOT NULL default '0',
hs_type varchar(10) NOT NULL default '',
hs_menu varchar(30) NOT NULL default '',
hs_sort varchar(10) NOT NULL default '',
hs_size_width int(11) NOT NULL default '0',
hs_size_height int(11) NOT NULL default '0',
hs_bg_color varchar(10) NOT NULL default '',
hs_bg_alpha varchar(10) NOT NULL default '',
hs_title_color varchar(10) NOT NULL default '',
hs_font_color varchar(10) NOT NULL default '',
hs_font_hover varchar(10) NOT NULL default '',
hs_border_width int(5) NOT NULL default '0',
hs_border_color varchar(10) NOT NULL default '',
hs_border_radius int(5) NOT NULL default '0',
hs_topic_type varchar(10) NOT NULL default '',
hs_topic_link varchar(1024) NOT NULL default '',
hs_topic_more varchar(20) NOT NULL default '',
hs_topic_bullet varchar(20) NOT NULL default '',
hs_title_1 varchar(50) NOT NULL default '',
hs_title_2 varchar(50) NOT NULL default '',
hs_title_3 varchar(50) NOT NULL default '',
hs_title_4 varchar(50) NOT NULL default '',
hs_title_5 varchar(50) NOT NULL default '',
hs_title_6 varchar(50) NOT NULL default '',
hs_title_7 varchar(50) NOT NULL default '',
hs_title_8 varchar(50) NOT NULL default '',
hs_title_9 varchar(50) NOT NULL default '',
hs_title_10 varchar(50) NOT NULL default '',
hs_title_11 varchar(50) NOT NULL default '',
hs_title_12 varchar(50) NOT NULL default '',
hs_title_13 varchar(50) NOT NULL default '',
hs_title_14 varchar(50) NOT NULL default '',
hs_title_15 varchar(50) NOT NULL default '',
hs_title_16 varchar(50) NOT NULL default '',
hs_title_17 varchar(50) NOT NULL default '',
hs_title_18 varchar(50) NOT NULL default '',
hs_title_19 varchar(50) NOT NULL default '',
hs_title_20 varchar(50) NOT NULL default '',
hs_title_21 varchar(50) NOT NULL default '',
hs_content_1 varchar(100) NOT NULL default '',
hs_content_2 varchar(100) NOT NULL default '',
hs_content_3 varchar(100) NOT NULL default '',
hs_content_4 varchar(100) NOT NULL default '',
hs_content_5 varchar(100) NOT NULL default '',
hs_content_6 varchar(100) NOT NULL default '',
hs_content_7 varchar(100) NOT NULL default '',
hs_link_1 varchar(1024) NOT NULL default '',
hs_link_2 varchar(1024) NOT NULL default '',
hs_link_3 varchar(1024) NOT NULL default '',
hs_link_4 varchar(1024) NOT NULL default '',
hs_link_5 varchar(1024) NOT NULL default '',
hs_link_6 varchar(1024) NOT NULL default '',
hs_link_7 varchar(1024) NOT NULL default '',
hs_link_8 varchar(1024) NOT NULL default '',
hs_link_9 varchar(1024) NOT NULL default '',
hs_link_10 varchar(1024) NOT NULL default '',
hs_file_1 varchar(255) NOT NULL default '',
hs_file_2 varchar(255) NOT NULL default '',
hs_file_3 varchar(255) NOT NULL default '',
hs_file_4 varchar(255) NOT NULL default '',
hs_file_5 varchar(255) NOT NULL default '',
hs_file_6 varchar(255) NOT NULL default '',
hs_file_7 varchar(255) NOT NULL default '',
hs_file_8 varchar(255) NOT NULL default '',
hs_file_9 varchar(255) NOT NULL default '',
hs_file_10 varchar(255) NOT NULL default '',
hs_file_sort varchar(50) NOT NULL default '',
hs_display tinyint(4) NOT NULL default '0',
hs_box_padding int(5) NOT NULL default '0',
PRIMARY KEY (hs_no)
) DEFAULT CHARSET=utf8";

mysql_query($sql) or die(mysql_error());
?>



