<?php

$sql = "CREATE TABLE $iw[theme_data_table](
td_no int(11) NOT NULL auto_increment,
td_code	varchar(30) NOT NULL default '',
ep_code varchar(30) NOT NULL default '',
mb_code varchar(30) NOT NULL default '',
td_image varchar(255) NOT NULL default '',
td_title varchar(255) NOT NULL default '',
td_price int(11) NOT NULL default '0',
td_sell int(11) NOT NULL default '0',
td_hit int(11) NOT NULL default '0',
td_recommend int(11) NOT NULL default '0',
td_datetime datetime NOT NULL default '0000-00-00 00:00:00',
td_display tinyint(4) NOT NULL default '0',
td_body_back_color varchar(10) NOT NULL default '',
td_menu_border_radius int(5) NOT NULL default '0',
td_menu_border_width int(5) NOT NULL default '0',
td_menu_back_opacity int(5) NOT NULL default '0',
td_menu_back_color varchar(10) NOT NULL default '',
td_menu_font_color varchar(10) NOT NULL default '',
td_menu_border_color varchar(10) NOT NULL default '',
td_menu_back_opacity_over int(5) NOT NULL default '0',
td_menu_back_color_over varchar(10) NOT NULL default '',
td_menu_font_color_over varchar(10) NOT NULL default '',
td_menu_border_color_over varchar(10) NOT NULL default '',
td_navi_border_radius int(5) NOT NULL default '0',
td_navi_border_width int(5) NOT NULL default '0',
td_navi_back_opacity int(5) NOT NULL default '0',
td_navi_back_color varchar(10) NOT NULL default '',
td_navi_font_color varchar(10) NOT NULL default '',
td_navi_border_color varchar(10) NOT NULL default '',
td_box_border_radius int(5) NOT NULL default '0',
td_box_border_width int(5) NOT NULL default '0',
td_box_back_opacity int(5) NOT NULL default '0',
td_box_back_color varchar(10) NOT NULL default '',
td_box_font_color varchar(10) NOT NULL default '',
td_box_border_color varchar(10) NOT NULL default '',
td_footer_border_radius int(5) NOT NULL default '0',
td_footer_border_width int(5) NOT NULL default '0',
td_footer_back_opacity int(5) NOT NULL default '0',
td_footer_back_color varchar(10) NOT NULL default '',
td_footer_font_color varchar(10) NOT NULL default '',
td_footer_border_color varchar(10) NOT NULL default '',
td_button_border_radius int(5) NOT NULL default '0',
td_button_border_width int(5) NOT NULL default '0',
td_button_back_opacity int(5) NOT NULL default '0',
td_button_back_color varchar(10) NOT NULL default '',
td_button_font_color varchar(10) NOT NULL default '',
td_button_border_color varchar(10) NOT NULL default '',
td_button_back_opacity_over int(5) NOT NULL default '0',
td_button_back_color_over varchar(10) NOT NULL default '',
td_button_font_color_over varchar(10) NOT NULL default '',
td_button_border_color_over varchar(10) NOT NULL default '',
td_page_border_radius int(5) NOT NULL default '0',
td_page_border_width int(5) NOT NULL default '0',
td_page_back_opacity int(5) NOT NULL default '0',
td_page_back_color varchar(10) NOT NULL default '',
td_page_font_color varchar(10) NOT NULL default '',
td_page_border_color varchar(10) NOT NULL default '',
td_page_back_opacity_over int(5) NOT NULL default '0',
td_page_back_color_over varchar(10) NOT NULL default '',
td_page_font_color_over varchar(10) NOT NULL default '',
td_page_border_color_over varchar(10) NOT NULL default '',
td_box_padding int(5) NOT NULL default '0',
PRIMARY KEY (td_no),
UNIQUE KEY td_code (td_code)
) DEFAULT CHARSET=utf8";

sql_query($sql);
?>